#!/bin/sh
export HOME=/var/lib/couchdb
export ERL_FLAGS="-couch_ini /usr/lib/couchdb/etc/default.ini /usr/lib/couchdb/etc/datadirs.ini /etc/couchdb/local.ini"
mkdir -p /var/run/couchdb
chown couchdb /var/run/couchdb
exec chpst -u couchdb:couchdb /usr/lib/couchdb/bin/couchdb

